configfile: "config/config_all_RNA.yaml"

include: "rules/ref.smk"
include: "rules/common.smk"
include: "rules/qc.smk"
include: "rules/mapping.smk"
include: "rules/diffexp.smk"



rule all:
    input:
        #"results/qc/multiqc_RNA.html",
        expand("results/star/{sample}/{sample}_Aligned.sortedByCoord.out.bam", sample=unique_samples),
        expand("results/star/{sample}/{sample}_Aligned.sortedByCoord.withRG.bam", sample=unique_samples),
        #expand("results/star_fusion/{sample}/star-fusion.fusion_predictions.abridged.tsv", sample=unique_samples),
        #"results/counts/combined_counts.tsv",
        #"results/deseq2/deseq2_results.tsv",