name: WGS
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - snakemake=8.9.0
  - fastqc=0.12.1
  - fastp=0.23.4
  - bwa-mem2=2.2.1
  - gffread=0.12.7
  - samtools=1.19
  - gatk4=4.5
  - picard=3.1.1
  - bedtools=2.31
  - graphviz=9.0.0
  #- gridss=2.13.2
  #- svaba=1.1.0
  - matplotlib=3.8.3
  - bcftools=1.19
  - jinja2=3.1.3
  - delly=1.2.6
  - r-devtools
  - pip
  - pip:
      - pysam==0.22
      - gdown==5.1.0

