name: VEP
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - snakemake=8.9.0
  - ensembl-vep=112.0
  - bcftools=1.20
  - perl-encode-locale=1.05
  - perl=5.32.1
  - vcf2maf=1.6.22