name: WGS_original
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - snakemake=8.9.0
  - fastp=0.23.4
  - bwa-mem2=2.2.1
  - samtools=1.19.2
  - gatk4=4.5
  - ascat=3.1.1
  - gridss=2.13
  - svaba=1.1.0
  - svdb=2.5.0  
  - bedtools=2.30.0
  - cnvkit=0.9.9
  - control-freec=11.6
  - graphviz=9.0.0
  - matplotlib=3.8.3
  - pygments=2.17.2
  - jinja2=3.1.3
  - bcftools=1.19
  - pip=24.0
  - pip:
      - pysam==0.22 


