configfile: "config/config_10samples.yaml"

include: "rules/ref.smk"
include: "rules/common.smk"
include: "rules/qc.smk"
include: "rules/mapping.smk"
include: "rules/calling.smk"



rule all:
    input:
        "results/qc/multiqc_ATAC.html",
        expand("results/deepTools/{sample}/{sample}.bigWig", sample=unique_samples),
        expand("results/macs2/{sample}/{sample}_peaks.narrowPeak", sample=unique_samples),
        