ref_genome: "/staging/leuven/stg_00096/references/chm13_v2.0_maskedY.rCRS/fasta/chm13v2.0_maskedY_rCRS.fa"
out_base: "/staging/leuven/stg_00096/home/rdewin/WGS/results"
log_dir: "/staging/leuven/stg_00096/home/rdewin/WGS/logs"
