name: ATAC
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - snakemake
  - samtools=1.19
  - bwa-mem2
  - macs2
  - deeptools
  - homer
  - fastp=0.23.4
  - gatk4=4.5
  - bedtools=2.31
  - graphviz=9.0.0
  - matplotlib
  - bcftools=1.19
  - jinja2=3.1.3
  - pip
  - pip:
      - pysam==0.22

